### ISSUE TITLE
No such file or directory (socket: /run/docker.sock) - exception while running deploy.sh

### ISSUE THREAD

**Issue by refacktor** [ratamacue/java-aws-fargate-hello-world#2]
deploy.sh was not successful:

```
INTERFACE=$(curl --silent http://169.254.169.254/latest/meta-data/network/interfaces/macs/)
SUBNET_ID=$(curl --silent http://169.254.169.254/latest/meta-data/network/interfaces/macs/${INTERFACE}/subnet-id)
ROLE_ARN=$(curl --silent http://169.254.169.254/latest/meta-data/iam/info|jq -r .InstanceProfileArn)
./deploy.sh -rolearn $ROLE_ARN -appname hello -subnets $SUBNET_ID -awsid ${ROLE_ARN:13:12} -dockerport 8080 -dockertag hello -clustername hello -cpu 1 -memory 2G

```

```
Exception in thread "main" javax.ws.rs.ProcessingException: org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
        at com.github.dockerjava.jaxrs.AuthCmdExec.execute(AuthCmdExec.java:30)
        at com.github.dockerjava.jaxrs.AuthCmdExec.execute(AuthCmdExec.java:17)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.AuthCmdImpl.exec(AuthCmdImpl.java:22)
        at com.cj.adsystems.deployment.fargate.Deployer.setupDocker(Deployer.java:272)
        at com.cj.adsystems.deployment.fargate.Deployer.deploy(Deployer.java:81)
        at com.davidron.fargatedemo.Deploy.main(Deploy.java:16)
Caused by: org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)

```

**Comment by vighneshpai-CT** [comment]
is this issue still there? or did u solved it?

**Comment by refacktor** [comment]
I decided not to use fargate for my project
